apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fleetman.com 
  - http:
      paths:
      - path: /fleetman-app
        backend:
          serviceName: fleetman-webapp
          servicePort: 80
      - path: /fleetman-queue
        backend:
          serviceName: fleetman-queue
          servicePort: 8161